if (select count() from systable where creator = 1 and table_name = 'st_err_track_det') = 0 then 
  CREATE TABLE "DBA"."st_err_track_det" (
    "c_doc_no" CHAR(25) NOT NULL,
    "n_inout" NUMERIC(1,0) NOT NULL,
    "n_seq" NUMERIC(11,0) NOT NULL DEFAULT 0,
    "n_org_seq" NUMERIC(11,0) NOT NULL DEFAULT 0,
    "c_item_code" CHAR(6) NOT NULL,
    "c_batch_no" CHAR(15) NOT NULL,
    "n_qty" NUMERIC(11,3) NOT NULL,
    "c_tray_code" CHAR(6) NOT NULL,
    "c_rack" CHAR(6) NULL,
    "c_rack_grp_code" CHAR(6) NOT NULL,
    "c_stage_code" CHAR(6) NULL,
    "c_godown_code" CHAR(6) NULL DEFAULT '-',
    "n_complete" NUMERIC(1,0) NULL DEFAULT 0,
    "n_hold_flag" NUMERIC(1,0) NULL DEFAULT 0,
    "c_reason_code" CHAR(6) NULL,
    "c_note" CHAR(40) NULL,
    "t_time" TIMESTAMP NULL,
    "c_chk_user" CHAR(10) NULL,
    "n_err_type" NUMERIC(1,0) NULL DEFAULT 0,
    "c_err_mark_user" CHAR(10) NULL,
    "t_err_time" TIMESTAMP NULL,
    "c_contra_item" CHAR(6) NULL,
    "c_pack_tray_code" CHAR(6) NULL,
    "c_counter_table_code" CHAR(6) NULL,
    "c_pick_user" CHAR(10) NULL,
    "t_pick_completed_time" TIMESTAMP NULL,
    "n_scheme_disc" NUMERIC(12,2) NULL DEFAULT 0,
    "n_schm_qty_2_schm_disc" NUMERIC(1,0) NULL DEFAULT 0,
    "n_ref_srno" NUMERIC(18,0) NULL DEFAULT 0,
    "c_ref_doc_no" CHAR(25) NULL,
    "t_ltime" TIMESTAMP NULL,
    "c_luser" CHAR(10) NULL,
    "n_carton_no" NUMERIC(9,0) NULL DEFAULT 0,
    "c_contra_batch" CHAR(15) NULL,
    "n_contra_qty" NUMERIC(11,3) NULL,
    "c_new_doc_no" CHAR(25) NOT NULL,
    "n_new_inout" NUMERIC(1,0) NOT NULL,
    "n_new_seq" NUMERIC(11,0) NOT NULL DEFAULT 0,
    PRIMARY KEY ( "c_doc_no" ASC, "n_inout" ASC, "n_seq" ASC, "c_tray_code" ASC, "c_rack_grp_code" ASC )
  ) IN "system";
end if;
commit work;
go